name: esmvaltool
channels:
  - conda-forge
  - esmvalgroup

dependencies:
  - python=3.6
  - ipykernel
  - pip
  - cython
  - esmpy
  - pynio
  - gdal
  - cf-units
  - cdo
  - ncl
  - nco
  - imagemagick
  - pyke
