name: base
channels:
  - conda-forge
dependencies:
  - ipykernel
  # core scipy packages
  - xarray
  - sparse
  - sympy
  # data science stuff
  - dask-ml
  - dask-xgboost
  - holoviews
  - panel
  - jupyter-panel-proxy
  - geoviews
  - hvplot
  - datashader
  - seaborn
  - altair
  - descartes
  - folium
  - vega
  - vega_datasets
  # geospatial
  - iris
  - cartopy
  - basemap
  - geopandas
  - rasterio
  - netcdf4
  - erddapy
  - pydap
  - h5py
  - h5netcdf
  - regionmask
  - rio-cogeo
  # geoscience-related
  - climlab
  - metpy
  - satpy
  - gsw
#  - eofs
  - esmpy
  - xesmf
  - windspharm
  # intake-related
  - intake
  - intake-xarray
  - intake-esm
  - fsspec
  - intake-stac
  - sat-stac
  - sat-search
  # zarr-related
  - zarr
  - numcodecs
  - python-blosc
  - lz4
  - gcsfs>=0.5.2
  - s3fs
  - tiledb-py
  # jupyter-related
  - ipyleaflet
#  - watermark
  # xarray-related
  - xgcm
#  - xrft
  - xhistogram
  - xlrd
  - xrviz
  - climpred
  - pytide
  - pyinterp
  # misc
  - python-wget
  - prefect
  - pyaerocom
  - pip:
    - intake_geopandas
    - git+https://github.com/NCAR/intake-esm.git@main
    - git+https://github.com/hhuangwx/cmaps.git#egg=cmaps
